sudo: false

language: python

python:
- "2.7"
- "3.5"
- "3.5-dev"  # 3.5 development branch
- "3.6"
- "3.6-dev"  # 3.6 development branch
- "3.7-dev"  # 3.7 development branch

addons:
  apt:
    packages:
    - oracle-java8-set-default

before_install:
- export PYTHON_MAJOR_VERSION=$(echo ${TRAVIS_PYTHON_VERSION:0:1})
- echo "Python major version is ${PYTHON_MAJOR_VERSION}"

install:
- pip install -r requirements/test.txt
- pip install tox-travis
- pip install codecov
- pip install .

before_script:
- curl -o /tmp/antlr.jar -O https://www.antlr.org/download/antlr-4.7.1-complete.jar
- java -Xmx500M -cp "/tmp/antlr.jar:$CLASSPATH"
  org.antlr.v4.Tool
  -package boltun.engine.grammar.antlr4
  -listener -visitor -Dlanguage=Python${PYTHON_MAJOR_VERSION}
  -lib sources/boltun/engine/grammar/antlr4
  sources/boltun/engine/grammar/antlr4/Antlr4Grammar.g4

script:
- tox

after_success:
- codecov

before_deploy:
- echo 'Deploying to PYPI'

deploy:
  provider: pypi
  user: meiblorn
  distributions: "sdist bdist_wheel"
  password:
    secure: JV/KtPFq86QjWTe40BeOGErwj3/8XS1mAsCs+cHlbzBlSdmxHiOLa8f7W8if9SgoLMI4Lp88jb06wQgKiTXFHoTc2EWnTpO3q9ANckFBT+pFbuJJmltIFEcCSTxifLbmdarepdxj6u1ddt/E5dEe855CjA09N6tQ12ImfiHjlNJVas0ZTvEJ7q1r1SWJIAgeL4PnNRurozolL4V/CZBElDU3grqvJpg8R8qh8r9+RBE7NGuK6a3RQd4uB9RIWfchbdPE4l6qtGlv2e1uizsKOIJB++d9aB7fdaVOD2jIrENwbfzYT0YhCQgXzMNQJ+8FwDmLI0higdm+rSHf6d4sOWzERtsvpPGu50yqFbYMrpDnMYhOwDFCFRwsgIfEiumcrW915PMuGK4BNW2zUouDt3dbvobNyef42wycWvm1Jap+cDVhm//q+1UNo8Bq5B4Nn6NcOZD9zQVIwWhQXbcPOMTx5hNrvPa3R7P8rUmOE2oUKjs3jheoufLO0o9oMprPv8GkA0jEYJu7SVYxEcjdfF80PywhrXntrHcsoVLxM8REcSjlhb48zsSay6XcZ6LP905DkePTUaG4wjumqCUk/roeDeHYbQMCz1ju5x2slYiI8wg/fGSYYxJt6JBvvhIvFvh8IqKuHUlQvL8lpAE+SJ8n8ogabS29IwWhxat0ibk=
  on:
    python: 3.6
    branch: master
    tags: true

after_deploy:
- echo 'Successfully deployed to PYPI'
